### PR TITLE
Command line interface and improvements

### PR DESCRIPTION
**Pull request by willemarcel**
Hi, Martijn

I was searching a tool to run queries on the overpass API and your project was almost exactly what I wanted, so I started building a command line interface and made some layout improvements. On the next days, I can put more some options on the CLI.

### CODE REVIEW

**Comment by itiboi** [comment]
Nice idea, especially useful when running tests by hand. Unfortunately I have no time to test it at the moment.

Please do not stick to the 80 line limit in PEP-8, I think 120 completely ok.

**Comment by mvexel** [comment]
I don't have time to test either :( but I agree the idea looks nice!

**Comment by willemarcel** [comment]
Hi, @mvexel 

If you want I can publish it on pypi.

**Comment by mvexel** [comment]
Go for it!

**Comment by mvexel** [comment]
Closing this in favor of the new PR here: #36

**Pull request closed without merging**
