### PR TITLE
Convenience properties for when API is next available

### PR DESCRIPTION
**Pull request by dericke**
Adds two properties that synthesize existing API status properties to answer the question, "when can I next query Overpass?" One returns an `int` of seconds until the API can next be queried (with `0` meaning the API is available now), the other returns a UTC `datetime` representing when the API can next be queried, or `None` if the API is available now. This is useful when the client has been making frequent calls to Overpass and may be blocked for a period of time.

### CODE REVIEW

**Comment by dericke** [comment]
There might be a better, more distinctive name I could use for the new properties.

**Comment by mvexel** [comment]
Cool, very useful. Did you look into why the 3.9 test failed

**Comment by dericke** [comment]
Sometime this week, I'll make a PR to use mock responses for the test that keeps failing, so we're not dependent on Overpass not having any issues at the particular moment the test is run.

**Comment by dericke** [comment]
Merged the mock_response from #153 into this PR, in the hopes that it makes everything a little easier to review.

**Pull request merged**
